### ISSUE TITLE
Navbar buttons

### ISSUE THREAD

**Issue by nikoto-** [nikoto-/Website#2]
To give it more of a "button" feeling, I'm trying to figure out the best way to "colorize" to green:
-text
-icon
-button bottom border

At the same time. Right now I have it set up so if you don't hover over the text, you can still have gray text and green underline/icon. The ideal way would be all three green on hover.

*Could probably do this with images, but eh. If you come up with something code-related, let me know. It's been a while and I know there's a way.

**Comment by paragon** [comment]
Did some changes and removed the images since they didn't flow really well with the site. I'd shy away from your old approach and instead use some open-source .svg 'font'. I used FontAwesome for the new images.
