### ISSUE TITLE
Three columns

### ISSUE THREAD

**Issue by nikoto-** [nikoto-/Website#3]
Need to set up a column structure for the grey content area.
Trying to figure out the optimal way to set this up.

3 divs? Using the <col> tag? Using css3?
I'll try and figure something out, feel free to leave any suggestions.

Each column will have a 120x120px green square with a minimal icon, followed by a short description grey text below. Maybe i'll describe my 3 main attributes.

**Comment by paragon** [comment]
Implemented: https://github.com/paragon/Website/commit/21443d81055e1abb997e29fd500e51d042c3ba22
